# Generated by Django 5.0.4 on 2024-04-16 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(max_length=3000)),
                ('search_text', models.TextField(max_length=2000)),
                ('source', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('topic', models.CharField(max_length=250)),
                ('question_type', models.CharField(max_length=100)),
                ('question_author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.CharField(max_length=100)),
                ('solution_media_source', models.URLField(blank=True, null=True)),
                ('solution_body', models.TextField(blank=True, max_length=3000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solverrapp.question')),
            ],
        ),
    ]
