# Generated by Django 5.0.4 on 2024-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0003_question_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uid',
            field=models.CharField(default='L1KZ8', max_length=10),
            preserve_default=False,
        ),
    ]
