# Generated by Django 5.0.4 on 2024-04-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0004_alter_question_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='uid',
        ),
    ]
