# Generated by Django 5.0.4 on 2024-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0006_question_display_body_question_display_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SCQ', 'Single Correct Question'), ('MCQ', 'Multiple Correct Question'), ('INT', 'Integer Type Question'), ('NUM', 'Numerical Type Question'), ('LONG', 'Subjective Type Question'), ('FILL', 'Fill in the Blank Question')], default='SCQ', max_length=100),
        ),
    ]
