# Generated by Django 5.0.4 on 2024-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0008_source_rename_topic_question_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sources',
        ),
        migrations.AddField(
            model_name='question',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='solverrapp.source'),
        ),
    ]
