# Generated by Django 5.0.4 on 2024-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0010_remove_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='search_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
