# Generated by Django 5.0.4 on 2024-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0011_alter_question_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('TXT', 'Rich-Text Based Solution'), ('IMG', 'Image Only Solution'), ('VID', 'Video Only Solution')], max_length=100),
        ),
    ]
