# Generated by Django 5.0.4 on 2024-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverrapp', '0012_alter_solution_solution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('IMG', 'Image Only Solution'), ('VID', 'Video Only Solution'), ('TXT', 'Rich-Text Based Solution')], max_length=100),
        ),
    ]
